// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using sistema;

namespace sistema.Migrations
{
    [DbContext(typeof(SistemaContext))]
    partial class SistemaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("sistema.Comentario", b =>
                {
                    b.Property<long>("ComentarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ComentarioTexto")
                        .HasColumnType("text");

                    b.Property<long>("NoticiaID")
                        .HasColumnType("bigint");

                    b.HasKey("ComentarioID");

                    b.HasIndex("NoticiaID");

                    b.ToTable("comentarios");
                });

            modelBuilder.Entity("sistema.Noticia", b =>
                {
                    b.Property<long>("NoticiaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityByDefaultColumn();

                    b.HasKey("NoticiaID");

                    b.ToTable("noticias");
                });

            modelBuilder.Entity("sistema.Comentario", b =>
                {
                    b.HasOne("sistema.Noticia", "Noticia")
                        .WithMany("Comentarios")
                        .HasForeignKey("NoticiaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Noticia");
                });

            modelBuilder.Entity("sistema.Noticia", b =>
                {
                    b.Navigation("Comentarios");
                });
#pragma warning restore 612, 618
        }
    }
}
